name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
        nim: ['devel']
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ci

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Run tests
        shell: bash
        run: |
          cd ci
          nimble --accept develop
          nimble test
